export const startupProfiles = {
  // Floor / Knowledge Space
  tansim: {
    slug: "tansim",
    name: "M/s. Tamil Nadu Startup and Innovation Mission",
    image: "/startup/tansim.png",
    space: "Floor / Knowledge Space",
  },
  nithilam: {
    slug: "nithilam",
    name: "M/s. Nithilam Private Limited",
    image: "/startup/nithilam-new.png",
    space: "Floor / Knowledge Space",
  },
  "nature-mills": {
    slug: "nature-mills",
    name: "M/s. Nature Mills",
    image: "/startup/nature-mills.png",
    space: "Floor / Knowledge Space",
  },
  insilicomics: {
    slug: "insilicomics",
    name: "M/s. Insilicomics",
    image: "/startup/insilicomics-new.png",
    space: "Floor / Knowledge Space",
  },
  "pechi-foods": {
    slug: "pechi-foods",
    name: "M/s. Pechi Foods Private Limited",
    image: "/startup/pechi-foods.png",
    space: "Floor / Knowledge Space",
  },
  innogreen: {
    slug: "innogreen",
    name: "M/s. Innogreen India Marketing",
    image: "/startup/innogreen-new.png",
    space: "Floor / Knowledge Space",
  },
  "leaders-desk": {
    slug: "leaders-desk",
    name: "M/s. Leaders Desk",
    image: "/startup/leaders-desk-new.png",
    space: "Floor / Knowledge Space",
  },
  "anga-information-technology": {
    slug: "anga-information-technology",
    name: "M/s. Anga Information Technology",
    image: "/startup/anga-information-technology-new.png",
    space: "Floor / Knowledge Space",
  },
  "yatvik-enterprises": {
    slug: "yatvik-enterprises",
    name: "M/s. Yatvik Enterprises",
    image: "/startup/yatvik-enterprises.png",
    space: "Floor / Knowledge Space",
  },
  "miyabi-agro": {
    slug: "miyabi-agro",
    name: "M/s. Miyabi Agro",
    image: "/startup/miyabi-agro-new.png",
    space: "Floor / Knowledge Space",
  },
  "mitti-lifetek-pharmadx": {
    slug: "mitti-lifetek-pharmadx",
    name: "M/s. Mitti Lifetek Pharmadx Private Limited",
    image: "/startup/mitti-lifetek-pharmadx-new.png",
    space: "Floor / Knowledge Space",
  },
  "karva-technologies": {
    slug: "karva-technologies",
    name: "M/s. Karva Technologies",
    image: "/startup/karva-technologies.png",
    space: "Floor / Knowledge Space",
  },
  "bits-informatics": {
    slug: "bits-informatics",
    name: "M/s. BiTs Informatics",
    image: "/startup/bits-informatics.png",
    space: "Floor / Knowledge Space",
  },
  "home-ideas-technologies": {
    slug: "home-ideas-technologies",
    name: "M/s. Home Ideas Technologies LLP",
    image: "/startup/home-ideas-technologies.png",
    space: "Floor / Knowledge Space",
  },
  "dc4-market-research": {
    slug: "dc4-market-research",
    name: "M/s. DC4 Market Research",
    image: "/startup/dc4-market-research.png",
    space: "Floor / Knowledge Space",
  },

  // Cabin Space
  "aviva-organics": {
    slug: "aviva-organics",
    name: "M/s. Aviva Organics Stores",
    image: "/startup/aviva-organics.png",
    space: "Cabin Space",
  },
  "dr-jini-narayan": {
    slug: "dr-jini-narayan",
    name: "Dr. Jini Narayan",
    image: "/startup/dr-jini-narayan-new.png",
    space: "Cabin Space",
  },
  oneomics: {
    slug: "oneomics",
    name: "M/s. Oneomics Private Limited",
    image: "/startup/oneomics-new.png",
    space: "Cabin Space",
  },
  thennaivanam: {
    slug: "thennaivanam",
    name: "M/s. Thennaivanam",
    image: "/startup/thennaivanam.png",
    space: "Cabin Space",
  },
  "sakthi-fertilizer": {
    slug: "sakthi-fertilizer",
    name: "M/s. Sakthi Fertilizer Company",
    image: "/startup/sakthi-fertilizer-new.png",
    space: "Cabin Space",
  },
  "dhivvya-bhalan": {
    slug: "dhivvya-bhalan",
    name: "Selvan. D. Dhivvya Bhalan, Kalaignar Karunanidhi Institution",
    image: "/startup/dhivvya-bhalan-new.png",
    space: "Cabin Space",
  },
  "bublbox-eretail": {
    slug: "bublbox-eretail",
    name: "M/s. Bublbox E-Retail Private Limited",
    image: "/startup/bublbox-eretail.png",
    space: "Cabin Space",
  },
  "croptwin-agro-tech": {
    slug: "croptwin-agro-tech",
    name: "M/s. CropTwin Agro Tech Pvt Ltd",
    image: "/startup/croptwin-agro-tech.png",
    space: "Cabin Space",
  },
  "prarthana-v": {
    slug: "prarthana-v",
    name: "Selvi. Prarthana V, Nehru Arts and Science College, CBE",
    image: "/startup/prarthana-v.png",
    space: "Cabin Space",
  },
  "univzero-technologies": {
    slug: "univzero-technologies",
    name: "M/s. UnivZero Technologies Pvt Ltd",
    image: "/startup/univzero-technologies.png",
    space: "Cabin Space",
  },
  "ss-tech": {
    slug: "ss-tech",
    name: "M/s. SS Tech",
    image: "/startup/ss-tech-new.png",
    space: "Cabin Space",
  },
  "valriya-vision": {
    slug: "valriya-vision",
    name: "M/s. Valriya Vision Pvt Ltd",
    image: "/startup/valriya-vision-new.png",
    space: "Cabin Space",
  },
  "ziwwit-sustainable-technologies": {
    slug: "ziwwit-sustainable-technologies",
    name: "M/s. Ziwwit Sustainable Technologies",
    image: "/startup/ziwwit-sustainable-technologies.png",
    space: "Cabin Space",
  },
  "sherpa-biotech": {
    slug: "sherpa-biotech",
    name: "M/s. Sherpa Biotech",
    image: "/startup/sherpa-biotech.png",
    space: "Cabin Space",
  },
  "bharath-biofarm": {
    slug: "bharath-biofarm",
    name: "M/s. Bharath Biofarm Pvt Ltd",
    image: "/startup/bharath-biofarm.png",
    space: "Cabin Space",
  },
  "skandax-nexus": {
    slug: "skandax-nexus",
    name: "M/s. Skandax Nexus",
    image: "/startup/skandax-nexus.png",
    space: "Cabin Space",
  },
  "tak-sfs": {
    slug: "tak-sfs",
    name: "M/s. TAK SFS Pvt Ltd",
    image: "/startup/tak-sfs.png",
    space: "Cabin Space",
  },
  quadrica: {
    slug: "quadrica",
    name: "M/s. Quadrica",
    image: "/startup/quadrica.png",
    space: "Cabin Space",
  },
  themolife: {
    slug: "themolife",
    name: "M/s. Themolife",
    image: "/startup/themolife.png",
    space: "Cabin Space",
  },
  "sparkle-consultancy": {
    slug: "sparkle-consultancy",
    name: "M/s. Sparkle Consultancy",
    image: "/startup/sparkle-consultancy.png",
    space: "Cabin Space",
  },
  "gudimangalam-fpo": {
    slug: "gudimangalam-fpo",
    name: "M/s. Gudimangalam FPO",
    image: "/startup/gudimangalam-fpo.png",
    space: "Cabin Space",
  },
  "sst-microgreen": {
    slug: "sst-microgreen",
    name: "M/s. SST Microgreen",
    image: "/startup/sst-microgreen.png",
    space: "Cabin Space",
  },
  "biofocus-scientific-solutions": {
    slug: "biofocus-scientific-solutions",
    name: "M/s. Biofocus Scientific Solution Pvt Ltd.",
    image: "/startup/biofocus-scientific-solutions.png",
    space: "Cabin Space",
  },
  "jithesh-vijayan": {
    slug: "jithesh-vijayan",
    name: "Dr. Jithesh Vijayan",
    image: "/startup/jithesh-vijayan.png",
    space: "Cabin Space",
  },
  "ainiminds-technologies": {
    slug: "ainiminds-technologies",
    name: "M/s. Ainiminds Technologies LLP",
    image: "/startup/ainiminds-technologies.png",
    space: "Cabin Space",
  },
  "uyrmey-bio-research": {
    slug: "uyrmey-bio-research",
    name: "M/s. Uyrmey Bio-Research Private Limited",
    image: "/startup/uyrmey-bio-research.png",
    space: "Cabin Space",
  },
  "ecozoe-technologies": {
    slug: "ecozoe-technologies",
    name: "M/s. Ecozoe Technologies Private Limited",
    image: "/startup/ecozoe-technologies.png",
    space: "Cabin Space",
  },

  // Cabin Space - newly onboarded startups
  "coimbatore-ai": {
    slug: "coimbatore-ai",
    name: "M/s. Coimbatore.ai",
    image: "/startup/coimbatore-ai.png",
    space: "Cabin Space",
  },
  "secular-foods": {
    slug: "secular-foods",
    name: "M/s. Secular Foods",
    image: "/startup/secular-foods.png",
    space: "Cabin Space",
  },
  "pothigai-innovations": {
    slug: "pothigai-innovations",
    name: "M/s. Pothigai Innovations",
    image: "/startup/pothigai-innovations.png",
    space: "Cabin Space",
  },
  "arshitha-food-products": {
    slug: "arshitha-food-products",
    name: "M/s. Arshitha Food Products",
    image: "/startup/arshitha-food-products.png",
    space: "Cabin Space",
  },
  "zero-hungry-foods": {
    slug: "zero-hungry-foods",
    name: "M/s. Zero Hungry Foods",
    image: "/startup/zero-hungry-foods.png",
    space: "Cabin Space",
  },
  "futurenet-technologies": {
    slug: "futurenet-technologies",
    name: "M/s. Futurenet Technologies",
    image: "/startup/futurenet-technologies.png",
    space: "Cabin Space",
  },
  "immk-chemtech": {
    slug: "immk-chemtech",
    name: "M/s. IMMK Chemtech Pvt. Ltd",
    image: "/startup/immk-chemtech.png",
    space: "Cabin Space",
  },
  "vebetos-world-wide": {
    slug: "vebetos-world-wide",
    name: "M/s. Vebetos World Wide Pvt. Ltd",
    image: "/startup/vebetos-world-wide.png",
    space: "Cabin Space",
  },
  "vel-nutri-foods": {
    slug: "vel-nutri-foods",
    name: "M/s. Vel Nutri Foods",
    image: "/startup/vel-nutri-foods.png",
    space: "Cabin Space",
  },
};

export const startupProfilesList = Object.values(startupProfiles);
